# Numpy

**Numpy** is an open-source Library that is used for scientific calculations.

## Characteristics of numpy
* (1). Homogeneous data type
* (2). memory less consume
* (3). Less time consume

In [2]:
# install numpy
!pip install numpy

In [3]:
# import numpy
import numpy as np

In [4]:
a = [1,3,4,24,4]
type(a)

list

In [6]:
b = np.array([1,3,45,2,4])
print(b)
type(b)

[ 1  3 45  2  4]


numpy.ndarray

In [7]:
# Dimension ===>
# 1-D element exist in x-direction
# 2-D element exist in x and y direction
# 3-D element exist in x, y, z direction

In [10]:
# shape ===> (rows,columns)
print("Total Shape : ",b.shape)

Total Shape :  (5,)


In [11]:
# size ===> row*column
print("Total size : ",b.size)

Total size :  5


In [12]:
# ndim ===> dimension
print("Total Dimension : ",b.ndim)

Total Dimension :  1


In [32]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)
type(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [33]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(b)
type(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [35]:
print("Total Shape : ",b.shape)
print("Total size : ",b.size)
print("Total Dimension : ",b.ndim)

Total Shape :  (3, 3)
Total size :  9
Total Dimension :  2


# how to create a user define array

In [27]:
a = []
size = int(input("Enter the size : "))
for i in range(size):
    val = int(input("Enter the value :"))
    a.append(val)
b = np.array(a)
b

Enter the size :  4
Enter the value : 1
Enter the value : 2
Enter the value : 34
Enter the value : 33


array([ 1,  2, 34, 33])

In [38]:
a = []
row = int(input("Enter row size : "))
col = int(input("Enter column size"))
for i in range(row):
    mylist = []
    for j in range(col):
        val = int(input("Enter the value : "))
        mylist.append(val)
    a.append(mylist)
b = np.array(a)
b

Enter row size :  3
Enter column size 2
Enter the value :  1
Enter the value :  2
Enter the value :  3
Enter the value :  4
Enter the value :  5
Enter the value :  6


array([[1, 2],
       [3, 4],
       [5, 6]])

# numpy function

In [39]:
# image ===> Pixels(0,255)px ===> 0px(black), 255px(white) ===> Normlize (0-1)px
    # (a). Black & White ===> height, width
    # (b). Colorfull ===> height, width, color_channel(RGB)

In [43]:
# Matirx ===> 
    # 1. Symmatric Matrix ===> rows = columns 
    # 2. Asymmatric Matrix ===> rows != columns 
    # 3. digonal position element ===> [(1,1),(2,2)......(n,n)]

In [41]:
# random number generation ===> random module

In [42]:
# Data Science ===> Simple Line Equation ===> y = mx+b
    # where
        # x,y ===> co-ordinates
        # m ===> weigth
        # b ===> intercept

### (1). Zeros() ===> It will create an array in which all the values are 0.

In [45]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [46]:
a = np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### (2). Ones() ===> It will create an array in which all the values are 1.

In [48]:
a = np.ones(3)
a

array([1., 1., 1.])

In [49]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### (3). eye() ===> It will create an array in which digonal position elements are 1 and rest all are 0.

In [50]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### (4). diag() ===> It will create an array in which we can cutomixe our digonal position elements.

In [52]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## (5). Random Module
* (a). OTP Generation
* (b). Dataset 1 dummy column add
* (c). randomly weights initialize

#### (a). randint(min_number, max_number, total_number)

In [55]:
a = np.random.randint(1,10,5)
a

array([5, 8, 5, 7, 1])

#### (b). rand(total_number) ===> range(0,1)

In [56]:
a = np.random.rand(5)
a

array([0.96309307, 0.24958365, 0.47896602, 0.40982893, 0.54588101])

#### (c). randn() ===> range(-3,+3)

In [57]:
a = np.random.randn(5)
a

array([-1.43656518,  0.21984359,  0.93310615, -0.96184305,  0.1424605 ])

#### (d). seed() ===> fix the generated values

In [66]:
np.random.seed(20)
a = np.random.randint(1,10,3)
a

array([4, 5, 7])

In [67]:
b = np.random.randint(1,10,3)
b

array([8, 3, 1])