In [1]:
import numpy as np

# View and Copy

In [6]:
# View means modification in original data
a = np.array([10,20,30,40,50,60,70,80,90,100])
b = a[2:5]
b[:] = 0
a

array([ 10,  20,   0,   0,   0,  60,  70,  80,  90, 100])

In [5]:
# copy means 
a = np.array([10,20,30,40,50,60,70,80,90,100])
b = a[2:5].copy()
b[:] = 0
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Reshapeing the data

In [7]:
# We konw that rows*columns = total_elements
# if we have total_element = 12
# [(1,12),(12,1),(2,6),(6,2),(3,4),(4,3)]

In [11]:
a = np.random.randint(1,50,12)
a

array([35, 10,  2, 31, 19,  6, 37, 11, 44, 23,  4, 10])

In [13]:
a.shape

(12,)

In [14]:
a.reshape(1,12)

array([[35, 10,  2, 31, 19,  6, 37, 11, 44, 23,  4, 10]])

In [15]:
a.reshape(12,1)

array([[35],
       [10],
       [ 2],
       [31],
       [19],
       [ 6],
       [37],
       [11],
       [44],
       [23],
       [ 4],
       [10]])

In [16]:
a.reshape(2,6)

array([[35, 10,  2, 31, 19,  6],
       [37, 11, 44, 23,  4, 10]])

In [17]:
a.reshape(6,2)

array([[35, 10],
       [ 2, 31],
       [19,  6],
       [37, 11],
       [44, 23],
       [ 4, 10]])

In [18]:
a.reshape(3,4)

array([[35, 10,  2, 31],
       [19,  6, 37, 11],
       [44, 23,  4, 10]])

In [19]:
a.reshape(4,3)

array([[35, 10,  2],
       [31, 19,  6],
       [37, 11, 44],
       [23,  4, 10]])

In [21]:
# it will generate a error because 3*5 = 15 not 12
a.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [22]:
a = np.random.randint(1,100,72)
a

array([75, 61, 63,  7, 62, 98, 73, 77, 42,  2, 94, 45, 70, 64, 35, 75, 66,
       69, 52, 63, 49,  2, 50, 71,  7, 47, 44,  3, 20,  1, 92, 31, 61, 37,
       35, 94, 89,  6, 98, 27, 73,  5, 42, 20, 87, 34, 21, 43, 31, 85, 75,
       38, 42, 88, 72, 81, 82, 19, 22, 34, 84, 88, 76, 15, 93,  4, 48, 17,
       50, 84, 57, 96])

In [23]:
a.reshape(1,72)

array([[75, 61, 63,  7, 62, 98, 73, 77, 42,  2, 94, 45, 70, 64, 35, 75,
        66, 69, 52, 63, 49,  2, 50, 71,  7, 47, 44,  3, 20,  1, 92, 31,
        61, 37, 35, 94, 89,  6, 98, 27, 73,  5, 42, 20, 87, 34, 21, 43,
        31, 85, 75, 38, 42, 88, 72, 81, 82, 19, 22, 34, 84, 88, 76, 15,
        93,  4, 48, 17, 50, 84, 57, 96]])

In [24]:
a.reshape(72,1)

array([[75],
       [61],
       [63],
       [ 7],
       [62],
       [98],
       [73],
       [77],
       [42],
       [ 2],
       [94],
       [45],
       [70],
       [64],
       [35],
       [75],
       [66],
       [69],
       [52],
       [63],
       [49],
       [ 2],
       [50],
       [71],
       [ 7],
       [47],
       [44],
       [ 3],
       [20],
       [ 1],
       [92],
       [31],
       [61],
       [37],
       [35],
       [94],
       [89],
       [ 6],
       [98],
       [27],
       [73],
       [ 5],
       [42],
       [20],
       [87],
       [34],
       [21],
       [43],
       [31],
       [85],
       [75],
       [38],
       [42],
       [88],
       [72],
       [81],
       [82],
       [19],
       [22],
       [34],
       [84],
       [88],
       [76],
       [15],
       [93],
       [ 4],
       [48],
       [17],
       [50],
       [84],
       [57],
       [96]])

In [25]:
a.reshape(2,36)

array([[75, 61, 63,  7, 62, 98, 73, 77, 42,  2, 94, 45, 70, 64, 35, 75,
        66, 69, 52, 63, 49,  2, 50, 71,  7, 47, 44,  3, 20,  1, 92, 31,
        61, 37, 35, 94],
       [89,  6, 98, 27, 73,  5, 42, 20, 87, 34, 21, 43, 31, 85, 75, 38,
        42, 88, 72, 81, 82, 19, 22, 34, 84, 88, 76, 15, 93,  4, 48, 17,
        50, 84, 57, 96]])

In [26]:
a.reshape(36,2)

array([[75, 61],
       [63,  7],
       [62, 98],
       [73, 77],
       [42,  2],
       [94, 45],
       [70, 64],
       [35, 75],
       [66, 69],
       [52, 63],
       [49,  2],
       [50, 71],
       [ 7, 47],
       [44,  3],
       [20,  1],
       [92, 31],
       [61, 37],
       [35, 94],
       [89,  6],
       [98, 27],
       [73,  5],
       [42, 20],
       [87, 34],
       [21, 43],
       [31, 85],
       [75, 38],
       [42, 88],
       [72, 81],
       [82, 19],
       [22, 34],
       [84, 88],
       [76, 15],
       [93,  4],
       [48, 17],
       [50, 84],
       [57, 96]])

In [27]:
a.reshape(3,24)

array([[75, 61, 63,  7, 62, 98, 73, 77, 42,  2, 94, 45, 70, 64, 35, 75,
        66, 69, 52, 63, 49,  2, 50, 71],
       [ 7, 47, 44,  3, 20,  1, 92, 31, 61, 37, 35, 94, 89,  6, 98, 27,
        73,  5, 42, 20, 87, 34, 21, 43],
       [31, 85, 75, 38, 42, 88, 72, 81, 82, 19, 22, 34, 84, 88, 76, 15,
        93,  4, 48, 17, 50, 84, 57, 96]])

In [28]:
a.reshape(24,3)

array([[75, 61, 63],
       [ 7, 62, 98],
       [73, 77, 42],
       [ 2, 94, 45],
       [70, 64, 35],
       [75, 66, 69],
       [52, 63, 49],
       [ 2, 50, 71],
       [ 7, 47, 44],
       [ 3, 20,  1],
       [92, 31, 61],
       [37, 35, 94],
       [89,  6, 98],
       [27, 73,  5],
       [42, 20, 87],
       [34, 21, 43],
       [31, 85, 75],
       [38, 42, 88],
       [72, 81, 82],
       [19, 22, 34],
       [84, 88, 76],
       [15, 93,  4],
       [48, 17, 50],
       [84, 57, 96]])

In [29]:
a.reshape(4,18)

array([[75, 61, 63,  7, 62, 98, 73, 77, 42,  2, 94, 45, 70, 64, 35, 75,
        66, 69],
       [52, 63, 49,  2, 50, 71,  7, 47, 44,  3, 20,  1, 92, 31, 61, 37,
        35, 94],
       [89,  6, 98, 27, 73,  5, 42, 20, 87, 34, 21, 43, 31, 85, 75, 38,
        42, 88],
       [72, 81, 82, 19, 22, 34, 84, 88, 76, 15, 93,  4, 48, 17, 50, 84,
        57, 96]])

In [30]:
a.reshape(18,4)

array([[75, 61, 63,  7],
       [62, 98, 73, 77],
       [42,  2, 94, 45],
       [70, 64, 35, 75],
       [66, 69, 52, 63],
       [49,  2, 50, 71],
       [ 7, 47, 44,  3],
       [20,  1, 92, 31],
       [61, 37, 35, 94],
       [89,  6, 98, 27],
       [73,  5, 42, 20],
       [87, 34, 21, 43],
       [31, 85, 75, 38],
       [42, 88, 72, 81],
       [82, 19, 22, 34],
       [84, 88, 76, 15],
       [93,  4, 48, 17],
       [50, 84, 57, 96]])

In [31]:
a.reshape(6,12)

array([[75, 61, 63,  7, 62, 98, 73, 77, 42,  2, 94, 45],
       [70, 64, 35, 75, 66, 69, 52, 63, 49,  2, 50, 71],
       [ 7, 47, 44,  3, 20,  1, 92, 31, 61, 37, 35, 94],
       [89,  6, 98, 27, 73,  5, 42, 20, 87, 34, 21, 43],
       [31, 85, 75, 38, 42, 88, 72, 81, 82, 19, 22, 34],
       [84, 88, 76, 15, 93,  4, 48, 17, 50, 84, 57, 96]])

In [32]:
a.reshape(12,6)

array([[75, 61, 63,  7, 62, 98],
       [73, 77, 42,  2, 94, 45],
       [70, 64, 35, 75, 66, 69],
       [52, 63, 49,  2, 50, 71],
       [ 7, 47, 44,  3, 20,  1],
       [92, 31, 61, 37, 35, 94],
       [89,  6, 98, 27, 73,  5],
       [42, 20, 87, 34, 21, 43],
       [31, 85, 75, 38, 42, 88],
       [72, 81, 82, 19, 22, 34],
       [84, 88, 76, 15, 93,  4],
       [48, 17, 50, 84, 57, 96]])

In [33]:
a.reshape(8,9)

array([[75, 61, 63,  7, 62, 98, 73, 77, 42],
       [ 2, 94, 45, 70, 64, 35, 75, 66, 69],
       [52, 63, 49,  2, 50, 71,  7, 47, 44],
       [ 3, 20,  1, 92, 31, 61, 37, 35, 94],
       [89,  6, 98, 27, 73,  5, 42, 20, 87],
       [34, 21, 43, 31, 85, 75, 38, 42, 88],
       [72, 81, 82, 19, 22, 34, 84, 88, 76],
       [15, 93,  4, 48, 17, 50, 84, 57, 96]])

In [35]:
a.reshape(9,8)

array([[75, 61, 63,  7, 62, 98, 73, 77],
       [42,  2, 94, 45, 70, 64, 35, 75],
       [66, 69, 52, 63, 49,  2, 50, 71],
       [ 7, 47, 44,  3, 20,  1, 92, 31],
       [61, 37, 35, 94, 89,  6, 98, 27],
       [73,  5, 42, 20, 87, 34, 21, 43],
       [31, 85, 75, 38, 42, 88, 72, 81],
       [82, 19, 22, 34, 84, 88, 76, 15],
       [93,  4, 48, 17, 50, 84, 57, 96]])

### arange()

In [36]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# Condition Selection in Numpy

In [37]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [38]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [39]:
b = a>10
b

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [40]:
b = a<10
b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [41]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [42]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [43]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [44]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

## Arithmetic operators in array

In [45]:
a+b

array([[ 6,  8],
       [10, 12]])

In [46]:
a-b

array([[-4, -4],
       [-4, -4]])

In [47]:
a*b  # worng way to multipation

array([[ 5, 12],
       [21, 32]])

In [49]:
a.dot(b) # for multipation

array([[19, 22],
       [43, 50]])

In [50]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
np.sum(a)

45

In [54]:
# axis = 1 means row
np.sum(a, axis=1)

array([ 6, 15, 24])

In [55]:
# axis = 0 means columns
np.sum(a, axis=0)

array([12, 15, 18])

### Unique() ===> It will return unique values or eliminate duplicate values.
* It will return 3 array
    * (1). Unique value's array.
    * (2). Indexing of original value.
    * (3). Returns frequency of each unique value.

In [56]:
a = np.array([1,2,1,2,3,3,4,3,2,3,5,6,3,2])
a

array([1, 2, 1, 2, 3, 3, 4, 3, 2, 3, 5, 6, 3, 2])

In [59]:
# True means we get the array
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  6, 10, 11], dtype=int64),
 array([2, 4, 5, 1, 1, 1], dtype=int64))

In [60]:
# False means we don't get array
np.unique(a, return_index=False, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 4, 5, 1, 1, 1], dtype=int64))

### linspace() ===> It will create an array in which difference of each value will be equal.

In [62]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## Stacking in Numpy

#### (1). hstack() ===> It will combined multiple arrays into horizontally.

In [63]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### (2).vstack() ===> It will combined multiple arrays into vertically.

In [64]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3 - Dim array

In [65]:
a = [[[1,2,3],[4,5,6],[7,8,9]]]
b = np.array(a)
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [66]:
b.ndim

3

In [67]:
b[0][0]

array([1, 2, 3])

In [68]:
b[0][1]

array([4, 5, 6])

In [69]:
b[0][2]

array([7, 8, 9])

In [71]:
b[0][2][0]

7