# LogsiticRegression ---> When we have Target data as categorical

1. LogisticRegression
2. Backend activition function (sigmoid)
3. probablity (0, 1)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\\DataSet\\covid_toy.csv")

In [3]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
df["fever"] = si.fit_transform(df[["fever"]])

In [6]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["gender"] = le.fit_transform(df["gender"])
df["cough"] = le.fit_transform(df["cough"])
df["city"] = le.fit_transform(df["city"])
df["has_covid"] = le.fit_transform(df["has_covid"])

In [8]:
df.head(3)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0

In [9]:
x = df.drop(columns = ["has_covid"])
y = df["has_covid"]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
lr = LogisticRegression()

In [14]:
lr.fit(x_train, y_train)

LogisticRegression()

In [15]:
y_pred = lr.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y_test, y_pred)

0.75

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test, y_pred)

array([[9, 4],
       [1, 6]], dtype=int64)

In [20]:
# [[tp, tn],
#  [fp, fn]]

# tp --> True positive
# tn --> True negative
# fp --> False positive
# fn --> False negative

In [21]:
df = pd.read_csv("D:\\DataSet\\Social_Network_Ads.csv")

In [22]:
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [23]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

In [25]:
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0

In [26]:
df["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split

x = df.drop(columns = ["Purchased"])
y = df["Purchased"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [29]:
lg.fit(x_train, y_train)

LogisticRegression()

In [30]:
y_pred = lg.predict(x_test)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(y_test, y_pred)

0.7375

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test, y_pred)

array([[49,  3],
       [18, 10]], dtype=int64)

In [35]:
df = pd.read_csv("D:\\DataSet\\placement.csv")

In [36]:
df.head(3)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [37]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [38]:
x = df.drop(columns = "placed")
y = df["placed"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [39]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [40]:
lg.fit(x_train, y_train)

LogisticRegression()

In [41]:
y_pred = lg.predict(x_test)

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0

In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[10,  0],
       [ 0, 10]], dtype=int64)

In [44]:
param_grid = [
    {'penalty':['l1','l2','elasticnet','none'],
    'C' : np.logspace(-4,4,20),
    'solver': ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter'  : [100,1000,2500,5000]
}
]

In [45]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(lg,param_grid = param_grid, cv = 3, verbose=True,n_jobs=-1)
clf

GridSearchCV(cv=3, estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                          'max_iter': [100, 1000, 2500, 5000],
                          'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                          'solver': ['lbfgs', 'newton-cg', 'liblinear', 'sag',
                                     'saga']}],
             verbose=True)

In [46]:
best_clf = clf.fit(x_train,y_train)
best_clf.best_estimator_

Fitting 3 folds for each of 1600 candidates, totalling 4800 fits


C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
2160 fits failed out of a total of 4800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\linear_mode

LogisticRegression(C=0.23357214690901212)

In [47]:
print(f'Accuracy - : {best_clf.score(x_train,y_train):.3f}')

Accuracy - : 0.975


In [48]:
df = pd.read_csv("D:\\DataSet\\insurance.csv")

In [49]:
df.head(3)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [50]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["smoker"] = le.fit_transform(df["smoker"])
df["region"] = le.fit_transform(df["region"])

In [52]:
df.head(3)

age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523
2   28    1  33.00         3       0       2   4449.4620

In [53]:
x = df.drop(columns = "charges")
y = df["charges"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [54]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [55]:
lr.fit(x_train, y_train)

LinearRegression()

In [56]:
y_pred = lr.predict(x_test)

In [57]:
from sklearn.metrics import r2_score

In [58]:
r2_score(y_test, y_pred)

0.7833463107364538

In [59]:
param_space = {'copy_X': [True,False], 
               'fit_intercept': [True,False], 
               'n_jobs': [1,5,10,15,None], 
               'positive': [True,False]}

In [60]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(lr,param_space, cv = 5, verbose=True,n_jobs=-1)
clf

GridSearchCV(cv=5, estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [1, 5, 10, 15, None],
                         'positive': [True, False]},
             verbose=True)

In [61]:
best_clf = clf.fit(x_train,y_train)
best_clf.best_estimator_

Fitting 5 folds for each of 40 candidates, totalling 200 fits


LinearRegression(n_jobs=1, positive=True)

In [62]:
print(f'Accuracy - : {best_clf.score(x_train,y_train):.3f}')

Accuracy - : 0.741


In [63]:
df = pd.read_csv("D:\\DataSet\\tips.csv")
df.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [66]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [67]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sex"] = le.fit_transform(df[["sex"]])
df["smoker"] = le.fit_transform(df[["smoker"]])
df["day"] = le.fit_transform(df[["day"]])
df["time"] = le.fit_transform(df[["time"]])

C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Khemr\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to

In [68]:
df.head(3)

total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3

In [69]:
x = df.drop(columns = ["total_bill"])
y = df["total_bill"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [70]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [71]:
lr.fit(x_train, y_train)

LinearRegression()

In [72]:
y_pred = lr.predict(x_test)

In [73]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6334779105328123

In [78]:
param_space = {'copy_X': [True,False], 
               'fit_intercept': [True,False], 
               'n_jobs': [1,5,10,15,None], 
               'positive': [True,False]}


In [79]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(lr, param_space, cv=5)

In [80]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LinearRegression(),
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [1, 5, 10, 15, None],
                         'positive': [True, False]})

In [81]:
print(f"Best Score: {grid_search.best_score_}")

Best Score: 0.5212670560903366
