In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(a)

numpy.ndarray

In [5]:
a.shape

(9,)

In [7]:
a.size

9

In [10]:
a.ndim

1

In [12]:
a = []
size = int(input("Enter the size :"))
for i in range(size):
    val = int(input("Enter the value :"))
    a.append(val)
b = np.array(a)
b

Enter the size : 3
Enter the value : 1
Enter the value : 2
Enter the value : 3


array([1, 2, 3])

In [15]:
a = np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
a = np.diag([24,224,232,2342])
a

array([[  24,    0,    0,    0],
       [   0,  224,    0,    0],
       [   0,    0,  232,    0],
       [   0,    0,    0, 2342]])

In [23]:
a = np.random.randint(1,10,5)
a

array([1, 8, 3, 4, 2])

In [25]:
a = np.random.rand(5)
a

array([0.01598328, 0.2907982 , 0.96474329, 0.76786457, 0.3977361 ])

In [26]:
a = np.random.rand(2,5)
a

array([[0.44542541, 0.47091363, 0.08572376, 0.24409932, 0.07902466],
       [0.22950257, 0.93626765, 0.40609515, 0.02225887, 0.46166571]])

In [27]:
a = np.random.randn(5)
a

array([ 0.73135015, -0.21084486, -2.00035257,  1.00917915,  0.09248216])

In [28]:
a = np.random.randn(2,5)
a

array([[-1.64784393, -1.94007471,  1.15601543, -1.71154826, -0.20503273],
       [ 0.31762725, -0.21493956, -0.48027839,  1.23473734, -0.98052382]])

In [30]:
np.random.seed(2)
a = np.random.randint(1,10,5)
a

array([9, 9, 7, 3, 9])

In [33]:
# view

In [31]:
a = np.random.randint(1,10,10)
a

array([8, 3, 2, 6, 5, 5, 6, 8, 4, 7])

In [32]:
b = a[2:5]
b[:] = 0
a

array([8, 3, 0, 0, 0, 5, 6, 8, 4, 7])

In [34]:
# copy

In [35]:
a = np.random.randint(1,10,10)
a

array([5, 4, 8, 7, 2, 4, 6, 9, 5, 7])

In [37]:
b = a[2:5].copy()
b[:] = 0
a

array([5, 4, 8, 7, 2, 4, 6, 9, 5, 7])

In [38]:
a = np.random.randint(1,10,12)
a

array([4, 3, 1, 5, 3, 5, 2, 8, 9, 3, 9, 8])

In [40]:
a.reshape(4,3)

array([[4, 3, 1],
       [5, 3, 5],
       [2, 8, 9],
       [3, 9, 8]])

In [42]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [45]:
a[a%2==0]

array([2, 4, 6, 8])

In [48]:
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)

In [49]:
a+b

array([[ 6,  8],
       [10, 12]])

In [50]:
a-b

array([[-4, -4],
       [-4, -4]])

In [52]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [53]:
np.sum(a)

10

In [54]:
np.sum(a,axis=1)

array([3, 7])

In [55]:
np.sum(a,axis=0)

array([4, 6])

In [56]:
a = np.array([1,2,1,2,3,3,4,3,2,3,5,6,3,2])
a

array([1, 2, 1, 2, 3, 3, 4, 3, 2, 3, 5, 6, 3, 2])

In [57]:
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  6, 10, 11], dtype=int64),
 array([2, 4, 5, 1, 1, 1], dtype=int64))

In [58]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [62]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])