In [1]:
import numpy as np

In [5]:
a = [1,2,3,4,5,6,7]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
np.shape(arr)

(7,)

In [7]:
np.size(arr)

7

In [8]:
np.ndim(arr)

1

In [3]:
a = [[1,2,3],[4,5,6]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6]])

# user define array

In [4]:
size = int(input("Enter the size : "))
mylist = []
for i in range(size):
    data = int(input("Enter the value : "))
    mylist.append(data)
arr = np.array(mylist)
arr

Enter the size :  4
Enter the value :  1
Enter the value :  2
Enter the value :  3
Enter the value :  4


array([1, 2, 3, 4])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.random.randint(1,10,5)

array([6, 4, 3, 6, 5])

In [20]:
np.random.randn(4)

array([ 1.63463741,  0.12809432, -0.39323072,  0.76421902])

In [21]:
np.random.rand(5)

array([0.16778382, 0.96640041, 0.88609009, 0.30134889, 0.69366843])

In [24]:
np.random.seed(20)
np.random.randint(1,10,5)

array([4, 5, 7, 8, 3])

In [26]:
a = np.random.randint(1,20,9)
a

array([ 1,  9, 17,  7,  7, 17, 10,  6,  8])

In [27]:
b = a[2:4]
b[:] = 0
a

array([ 1,  9,  0,  0,  7, 17, 10,  6,  8])

In [28]:
a = np.random.randint(1,20,9)
a

array([ 6,  3,  7, 14, 12,  4, 11, 12, 14])

In [29]:
b = a[2:5].copy()
b[:] = 0
a

array([ 6,  3,  7, 14, 12,  4, 11, 12, 14])

In [30]:
a

array([ 6,  3,  7, 14, 12,  4, 11, 12, 14])

In [31]:
a.reshape([3,3])

array([[ 6,  3,  7],
       [14, 12,  4],
       [11, 12, 14]])

In [34]:
arr = np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [36]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr%2!=0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False])

In [38]:
a = np.array([1,2,3,4]).reshape([2,2])
b = np.array([5,6,7,8]).reshape([2,2])

In [39]:
a+b

array([[ 6,  8],
       [10, 12]])

In [40]:
a-b

array([[-4, -4],
       [-4, -4]])

In [41]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [46]:
np.sum(a)

10

In [47]:
np.sum(a, axis=0)

array([4, 6])

In [48]:
np.sum(a, axis=1)

array([3, 7])

In [50]:
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4]),
 array([0, 1, 2, 3], dtype=int64),
 array([1, 1, 1, 1], dtype=int64))

In [51]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [52]:
a

array([[1, 2],
       [3, 4]])

In [53]:
b

array([[5, 6],
       [7, 8]])

In [56]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [57]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])